PORT= 8888 # Server PORT
CONSUMER_API_KEY= 'TWITTER CONSUMER KEY' #TWITTER CONSUMER KEY
CONSUMER_API_SECRET_KEY= 'TWITTER CONSUMER SECRET' #TWITTER CONSUMER SECRET
AUTH_URL= 'https://api.twitter.com/oauth2/token' #TWITTER OAUTH2.0 URL
SEARCH_URL= 'https://api.twitter.com/1.1/search/tweets.json' #TWITTER SEARCH URL
USER_TIMELINE_URL= 'https://api.twitter.com/1.1/statuses/user_timeline.json' #TWITTER USER TIMELINE URL